<?php

/**
 * @file
 *
 *
 * This authentication module is based on idea's from the simpleSAMLAuth module,
 * which can be found at http://code.google.com/p/drupalsimplesaml/.
 *
 */

/**
 * Implementation of hook_perm().
 */
function ding_wayf_perm() {
  return array(
     'configure wayf',
    );
}

/**
 * Implementation of hook_menu().
 */
function ding_wayf_menu() {
  $items = array();

  // Administation interface.
  $items['admin/settings/ding/wayf'] = array(
   'title' => t('Ding! WAYF'),
   'description' => t('Configure Ding! WAYF'),
   'page callback' => 'drupal_get_form',
   'page arguments' => array('ding_wayf_admin_settings_form'),
   'access arguments' => array('configure wayf'),
   'file' => 'includes/ding_wayf.admin.inc',
  );

  // WAYF login callback.
  $items['wayf'] = array(
    'title' => t('Logon to the site'),
    'description' => t('Provides WAYF login.'),
    'page callback' => 'ding_wayf_redirect_login',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function ding_wayf_redirect_login() {
  global $user;

  // Load configuration, if not defined, set default values.
  $config = variable_get('ding_wayf', array());
  if (empty($config)) {
    $config = array(
      'installdir' => '/var/simplesamlphp',
      'sp' => 'default-sp',
      'data_field' => 'schacPersonalUniqueID',
      'data_field_id' => 'CPR',
      'https' => TRUE,
    );
  }

  // Load simple saml php.
  require_once($config['installdir'] . '/lib/_autoload.php');

  // TODO: Test for simple saml php version

  // Check if user is already logged in, if not continue with wayf.
  if ($user->uid == 0) {
    // Get saml connection.
    $saml = ding_wayf_get_saml_connection($config['sp']);

    // User is not logged into drupal, check wayf
    if ($saml->isAuthenticated()) {
      // Get CPR number to log into Ding! provider.
      $saml_attributes = $saml->getAttributes();
      $creds['name'] = ding_wayf_get_credentials($saml_attributes[$config['data_field']], $config['data_field_id']);
      print_r($creds);
    }
    else {
      $saml->requireAuth();
    }
  }
  else {
    // Send the user to her/his user page.
    drupal_goto('/user/' . $user->uid);
  }
  return;
}

function ding_wayf_get_credentials($data, $field) {
  return substr($data[0], strpos($data[0], $field) + strlen($field) + 1);
}

function ding_wayf_get_saml_connection($sp) {
  return new SimpleSAML_Auth_Simple($sp);
}