<?php

/**
 * Implementation of hook_perm().
 */
function ding_wayf_perm() {
  return array(
     'configure wayf',
    );
}

/**
 * Implementation of hook_menu().
 */
function ding_wayf_menu() {
  $items = array();

  // Administation interface.
  $items['admin/settings/ding/wayf'] = array(
   'title' => t('Ding! WAYF'),
   'description' => t('Configure Ding! WAYF'),
   'page callback' => 'drupal_get_form',
   'page arguments' => array('ding_wayf_admin_settings_form'),
   'access arguments' => array('configure wayf'),
   'file' => 'includes/ding_wayf.admin.inc',
  );

  // WAYF login callback.
  $items['wayf'] = array(
    'title' => t('Logon to the site'),
    'description' => t('Provides WAYF login.'),
    'page callback' => 'ding_wayf_redirect_login',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function ding_wayf_redirect_login() {
//  global $user;
//  global $as;
//  global $saml_attributes;
//
//  if ($user->uid == 0 || $user->uid == 1) {
//    if ($user->uid == 0) {
//      /* Require the user to be authentcated. */
//      $as->requireAuth();
//    } else {
//      $output .= 'I am drupal, here me roar';
//    }
//  } else {
//    drupal_goto('/user/' . $user->uid);
//  }
//
//  return $output;
  return 'Not ready yet';
}